added Drawer and updated logic of MainActivity
codex-team/hawk.android.app pull request #22
Opened 2020-04-24 20:08 UTC by YorkIsMine

2020-04-24 20:43 UTC, Shiplayer requested changes

2020-04-24 20:43 UTC, Shiplayer commented on codexbl/src/main/java/so/codex/codexbl/entity/Workspace.kt
> +        val projects: List<Project>? = null
зачем он по умолчанию null? может стоило бы делать просто listOf()?

2020-04-24 20:43 UTC, Shiplayer commented on app/src/main/res/layout/view_test.xml
> +</androidx.drawerlayout.widget.DrawerLayout>
зачем этот лейаут?

2020-04-24 20:43 UTC, Shiplayer commented on app/src/main/res/layout/activity_main.xml
> +    </androidx.coordinatorlayout.widget.CoordinatorLayout>
Может стоит все таки сделать просто `FrameLayout` вместо `CoordinatorLayout`? А то нет никакого смысла от `CoordinatorLayout`

2020-04-24 20:43 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/garage/GarageFragment.kt
> +                list.addAll(w.projects!!)
если проекты могут быть null, то где проверка, что она действительно не null? Мы же не хотим, чтоб мы получили NPE?

2020-04-24 20:43 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/adapters/WorkspaceItemAdapter.kt
> +    }
У нас элементы не кликабельные?

2020-04-24 20:43 UTC, Shiplayer commented on uicomponent/src/main/res/values/attrs.xml
> +        <attr name="src_ws" format="reference" />
почему не просто src?

2020-04-24 20:46 UTC, YorkIsMine commented on uicomponent/src/main/res/values/attrs.xml
> +        <attr name="src_ws" format="reference" />
потому что студия ругалась бы и не запустила

2020-04-24 20:46 UTC, YorkIsMine commented on app/src/main/java/so/codex/hawk/adapters/WorkspaceItemAdapter.kt
> +    }
пока это так

2020-04-24 20:47 UTC, YorkIsMine commented on app/src/main/res/layout/view_test.xml
> +</androidx.drawerlayout.widget.DrawerLayout>
Для дровера

2020-04-24 20:47 UTC, YorkIsMine commented on app/src/main/res/layout/activity_main.xml
> +    </androidx.coordinatorlayout.widget.CoordinatorLayout>
Не подумал как-то

2020-04-24 20:48 UTC, YorkIsMine commented on codexbl/src/main/java/so/codex/codexbl/entity/Workspace.kt
> +        val projects: List<Project>? = null
не подумал об этом

2020-04-24 20:48 UTC, YorkIsMine commented on app/src/main/java/so/codex/hawk/ui/garage/GarageFragment.kt
> +                list.addAll(w.projects!!)
ну это вытекает из того, что по умолчанию налл..однако я знаю на 100 процентов, что здесь налла не будет

2020-04-24 20:49 UTC, Shiplayer commented on app/src/main/res/layout/view_test.xml
> +</androidx.drawerlayout.widget.DrawerLayout>
можешь показать место, где он используется?

2020-04-24 20:50 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/garage/GarageFragment.kt
> +                list.addAll(w.projects!!)
ты вот знаешь, а я могу забыть об этом или какой либо другой случай может произойти, когда projects будет null'ом

2020-04-24 20:51 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/adapters/WorkspaceItemAdapter.kt
> +    }
пока это так, мы не можем влить это в мастер

2020-04-25 14:33 UTC, YorkIsMine commented on app/src/main/res/layout/view_test.xml
> +</androidx.drawerlayout.widget.DrawerLayout>
это просто лэйаут для тестов

2020-04-25 15:54 UTC, Shiplayer commented on app/src/main/res/layout/view_test.xml
> +</androidx.drawerlayout.widget.DrawerLayout>
зачем он тогда в пулл реквесте?

2020-04-28 14:10 UTC, Shiplayer requested changes
Почему вообще добавлены png в ресурсы? почему они не добавлены как векторные изображения?

2020-04-28 14:10 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/adapters/WorkspaceItemAdapter.kt
> +            if (view is WorkspaceItemView) {
ну вообще, у ViewHolder есть поле itemView, да и нужда в объявлении поля view отпадает

2020-04-28 14:10 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/adapters/WorkspaceItemAdapter.kt
> +                        .into(view.logoImage)
А если произойдет ошибка во время получения картинки? ну например, ссылка будет не валидная или инет отвалится?

2020-04-28 14:10 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/adapters/WorkspaceItemAdapter.kt
> +                        .into(view.logoImage)
а может это как-то можно совместить с этим куском кода?
```
                    if (workspace.image.isNotEmpty()) {
                    Picasso.get()
                        .load(workspace.image)
                        .error(R.drawable.ic_error_outline_black_24dp)
                        .into(view.logoImage)
                } else view.setDefaultImage()
```

2020-04-28 14:10 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/adapters/WorkspaceItemAdapter.kt
> +                }
как то сложно

2020-04-28 14:10 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/adapters/WorkspaceItemAdapter.kt
> +            WorkspaceItemView(parent.context)
вот поэтому у тебя там такие элементы были
![image](https://user-images.githubusercontent.com/10272247/80494631-8ab95b80-896f-11ea-851c-24859b663864.png)

2020-04-28 14:10 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/adapters/WorkspaceItemAdapter.kt
> +        workspaces.add(workspaces.size, lastWorkspace)
а когда вставляем последний элемент, нам не надо уведомлять об этом адаптер?

2020-04-28 14:10 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/MainActivity.kt
> +        presenter.attached(this)
почему аттачим до того, как установим контент? ведь мы можем получить npe, если в аттаче надо будет что-то сделать со вьюшкой

2020-04-28 14:10 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/adapters/WorkspaceItemAdapter.kt
> +                if (workspace.image == "NO_IMG") {
почему мы вообще можем класть туда "NO_IMG"? почему мы не можем это оставить на пикасо?

2020-04-28 14:10 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/garage/GarageFragment.kt
> +                list.addAll(w.projects!!)
может тут все таки надо что то сделать с этим?

2020-04-28 14:10 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/login/SignInFormFragment.kt
> +    ISignInView {
верни его обратно на 20 строчку

2020-04-28 14:10 UTC, Shiplayer commented on app/src/main/res/layout/activity_main.xml
> +    </androidx.coordinatorlayout.widget.CoordinatorLayout>
может все таки с этим надо что то сделать?

2020-04-28 14:10 UTC, Shiplayer commented on app/src/main/res/layout/drawer_header.xml
> +        android:src="@drawable/la"
что такое la?

2020-04-28 14:10 UTC, Shiplayer commented on app/src/main/res/layout/drawer_header.xml
> +        android:text="vladal56hack@yandex.ru"
может тут надо использовать tools:text?

2020-04-28 14:10 UTC, Shiplayer commented on app/src/main/res/layout/drawer_header.xml
> +        android:id="@+id/h_email"
h_email?

2020-04-28 14:10 UTC, Shiplayer commented on app/src/main/res/layout/drawer_header.xml
> +        android:id="@+id/h_user_icon"
h_user_icon?

2020-04-28 14:10 UTC, Shiplayer commented on app/src/main/res/layout/drawer_header.xml
> +        android:id="@+id/h_user_icon"
может по нормальному назовем?

2020-04-28 14:10 UTC, Shiplayer commented on codexbl/src/main/java/so/codex/codexbl/entity/Workspace.kt
> +        val image: String = "NO_IMG",
почему не просто пустую строчку сделать? тогда в адапторе воткнется дефолтная картинка

2020-04-28 14:10 UTC, Shiplayer commented on codexbl/src/main/java/so/codex/codexbl/presenter/GaragePresenter.kt
> +    private val profileInteractor: IProfileInteractor = ProfileInteractor() //ToDo to put in Koin
выполни свою тодошку

2020-04-28 14:10 UTC, Shiplayer commented on codexbl/src/main/java/so/codex/codexbl/presenter/GaragePresenter.kt
> +                    it.printStackTrace()
а сообщение мы не хотим показать, что чтото пошло не так?

2020-04-28 14:10 UTC, Shiplayer commented on hawkapi/src/main/java/so/codex/hawkapi/ProfileApiMethodsImpl.kt
> +    override fun me(): Single<ProfileResponse> {
может надо было назвать метод getProfileInfo?

2020-04-28 14:10 UTC, Shiplayer commented on uicomponent/src/main/java/so/codex/uicomponent/recyclerview/items/WorkspaceItemView.kt
> +            recycle()
я, конечно же, не уверен, что мы будем выставлять картинку для элемента в xml, но это на твое усмотрение

2020-04-28 14:10 UTC, Shiplayer commented on uicomponent/src/main/java/so/codex/uicomponent/recyclerview/items/WorkspaceItemView.kt
> +            ContextCompat.getDrawable(context, R.drawable.clicked_back)
зачем так сложно? разве мы не можем получить элемент с помощью `view.container_workspace`?

2020-04-28 14:10 UTC, Shiplayer commented on uicomponent/src/main/java/so/codex/uicomponent/recyclerview/items/WorkspaceItemView.kt
> +        findViewById<RelativeLayout>(R.id.container_workspace).background =
аналогично

2020-04-28 14:10 UTC, Shiplayer commented on uicomponent/src/main/res/drawable/clicked_back.xml
> +</shape>
что-то это не совсем похоже на то, что требуется в дизайне
![image](https://user-images.githubusercontent.com/10272247/80497058-a114e680-8972-11ea-9316-b85b8dd9173e.png)

2020-04-28 14:10 UTC, Shiplayer commented on uicomponent/src/main/res/drawable/disabled.xml
> +</shape>
можешь пояснить, зачем это нужно?

2020-04-28 14:10 UTC, Shiplayer commented on uicomponent/src/main/res/layout-xxxhdpi/workspace_item.xml
> +    android:background="@color/disabled"
зачем нам такой цвет? это такой же цвет, как и бэкграунд?

2020-04-28 14:10 UTC, Shiplayer commented on uicomponent/src/main/res/layout-xxxhdpi/workspace_item.xml
> +        android:src="@android:color/background_light" />
tools:src?

2020-04-28 14:10 UTC, Shiplayer commented on uicomponent/src/main/res/layout-xxxhdpi/workspace_item.xml
> +        android:src="@android:color/background_light" />
и зачем мы туда такой бэкграунд вставляем?

2020-04-28 20:37 UTC, YorkIsMine commented on uicomponent/src/main/res/drawable/clicked_back.xml
> +</shape>
![image](https://user-images.githubusercontent.com/45906131/80535245-2a471000-89a9-11ea-86b8-607c6b8846ca.png)

2020-05-02 18:17 UTC, Shiplayer requested changes

2020-05-02 18:17 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/CharsRemover.kt
> +fun removeUselessChars(str: String): String {
зачем надо было выносить в отдельный файл? почему нельзя было сделать просто как приватный метод в классе `ImageProvider`?

2020-05-02 18:17 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ImageProvider.kt
> +    fun load(width: Int, height: Int, density: Float, viewColor: Int, workspace: Workspace): Bitmap {
можно пренебречь шириной или высотой, так как у нас должна быть только квадратная картинка

2020-05-02 18:17 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/adapters/WorkspaceItemAdapter.kt
> +                    view.logoImage.setOnClickListener {
тут будет бага

2020-05-02 18:17 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/adapters/WorkspaceItemAdapter.kt
> +                    view.logoImage.setOnClickListener {
данное событие будет вызываться даже если этот элемент не будет Add workspace

2020-05-02 18:17 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/MainActivity.kt
> +        header_email.text = profile.email ?: "NULLLLLLL" // is null
что за `NULLLLLLL`?

2020-05-02 18:17 UTC, Shiplayer commented on codexbl/src/main/java/so/codex/codexbl/presenter/GaragePresenter.kt
> +                     throw Exception("Error with getting Profile")
`view?.showErrorMessage(it.message ?: " something went wrong!")` не?

2020-05-02 18:17 UTC, Shiplayer commented on uicomponent/src/main/java/so/codex/uicomponent/recyclerview/items/ProjectItemView.kt
>      fun setDefaultImage() {
может тогда уже стоит этот метод удалить?

2020-05-02 18:17 UTC, Shiplayer commented on uicomponent/src/main/res/layout-xxxhdpi/workspace_item.xml
>          android:textColor="#DBE6FF" />
давай вынесем цвет для текста в colors.xml?

2020-05-03 05:43 UTC, Shiplayer requested changes

2020-05-03 05:43 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ImageProvider.kt
>              canvas.drawText(firstChar, centerX, centerY, fontPaint)
почему бы это не вынести в отдельный приватный метод?

2020-05-03 05:43 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ImageProvider.kt
>                  }
почему ниже догадался использовать `joinToString`, а тут нет? Или тут есть какие то веские причины его не использовать?

2020-05-09 20:10 UTC, Shiplayer requested changes

2020-05-09 20:10 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/adapters/WorkspaceItemAdapter.kt
> +                .into(view.logoImage)
зачем для этого надо было использовать Picasso? разве мы не можем сделать вот так `view.logoImage.setImageDrawable(R.drawable.add_workspace)`?

2020-05-09 20:10 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/adapters/WorkspaceItemAdapter.kt
> +            setAddWorkspaceData()
как то больно сильно на методы разбил, это уже борщ, где в каждом методе по одной строчке

2020-05-25 08:27 UTC, Shiplayer requested changes

2020-05-25 08:27 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/DefaultImageLoader.kt
> +        fun get(name: String, id: String): DefaultImageLoader = DefaultImageLoader(name, id)
зачем нам надо каждый раз создавать новый экземпляр `DefaultImageLoader`? почему мы не можем сразу получить битмап?

2020-05-25 08:27 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/WorkspaceViewModelDiffUtil.kt
> +class WorkspaceViewModelDiffUtil : DiffUtil.Callback() {
задокументируй, пожалуйста

2020-05-25 08:27 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/MainActivity.kt
> +
здесь тоже бы документацию написать

2020-05-25 08:27 UTC, Shiplayer commented on app/build.gradle
> +    implementation libs.coreKtx
если решил так сделать, то может и все остальные привести к такому виду?

2020-05-25 08:27 UTC, Shiplayer commented on codexbl/src/main/java/so/codex/codexbl/presenter/GaragePresenter.kt
> +    private var cachedWorkspaces: List<WorkspaceViewModel> = listOf()
тоже задокументируй

2020-05-25 08:27 UTC, Shiplayer commented on codexbl/src/main/java/so/codex/codexbl/view/IGarageView.kt
> +    data class WorkspaceViewModel(
документация

2020-05-25 08:27 UTC, Shiplayer commented on dependencies.gradle
> +]
может все таки стоит вынести номер версии в `ext.versions`?

2020-05-25 08:27 UTC, Shiplayer commented on uicomponent/src/main/java/so/codex/uicomponent/recyclerview/items/WorkspaceItemView.kt
> +    var isViewSelected: Boolean = false
документация

2020-05-25 08:27 UTC, Shiplayer commented on uicomponent/src/main/java/so/codex/uicomponent/recyclerview/items/WorkspaceItemView.kt
> +    fun setDefaultImage() {
пометь такой метод, как деприкейтед

2020-05-25 08:27 UTC, Shiplayer commented on uicomponent/src/main/res/values/attrs.xml
> +        <attr name="src_ws" format="reference" />
чтобы так не делать, советую обратить внимание на 4 строчку в данном файле, и в каких объявленных стилях он используется

2020-05-25 08:27 UTC, Shiplayer commented on uicomponent/src/main/java/so/codex/uicomponent/recyclerview/items/WorkspaceItemView.kt
> +import android.graphics.*
разберись с этой звездочкой

2020-05-25 08:27 UTC, Shiplayer commented on uicomponent/src/main/res/values/colors.xml
> +    <color name="disabled">#242732</color>
он где нибудь используется?

2020-05-25 08:27 UTC, Shiplayer commented on uicomponent/src/main/res/drawable/disabled.xml
> +</shape>
зачем данный файл нужен?

2020-07-28 20:20 UTC, closed without merging