Feature/garage
codex-team/hawk.android.app pull request #4
Opened 2019-08-21 20:52 UTC by Shiplayer

Изменен экран для регистрации, переделана под форму входа.
Добавлен экран гаража, поддерживает сессию.
Добавлено восстановлении сессии, если токен стал невалидным
Добавлен поиск без функционала, с некоторыми анимационными действиями
Добавлена возможность обновлять список по свайпу вниз
Добавлен функционал для получения данных из воркспейсов
Добавлены дефолтные логотипы для проектов

2019-09-03 21:56 UTC, nikmel2803 approved these changes

2019-09-10 09:27 UTC, neSpecc requested changes
Код не продокументирован

2019-09-11 12:01 UTC, kabachook requested changes

2019-09-11 12:01 UTC, kabachook commented on SourceInterfaces/src/main/java/so/codex/sourceinterfaces/response/WorkspaceResponse.kt
> +data class WorkspaceResponse<T : WorkspaceEntity>(
doc

2019-09-11 12:01 UTC, kabachook commented on app/build.gradle
> +    /*flavorDimensions 'hawk'
????

2019-09-11 12:01 UTC, kabachook commented on app/src/main/java/so/codex/hawk/adapters/ProjectsItemsAdapter.kt
> +    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ProjectItemViewHolder {
минимальные доки хотя бы

2019-09-11 12:01 UTC, kabachook commented on app/src/main/java/so/codex/hawk/base/HawkApplication.kt
> +class HawkApplication : MultiDexApplication() {
описать почему такое наследование

2019-09-11 12:01 UTC, kabachook commented on app/src/main/java/so/codex/hawk/base/HawkApplication.kt
>  import so.codex.codexbl.main.StartKoinComponent
`StartKotlinComponent`?

2019-09-11 12:11 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/base/HawkApplication.kt
> +class HawkApplication : MultiDexApplication() {
Ну, вообще, андройд программист должен знать, что если приложение не влезает в один dex не влезает 64к функций, то самый главный класс нужно унаследовать от MultiDexApplication, чтоб он смог собрать более чем один dex файл

2019-09-11 12:14 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/adapters/ProjectsItemsAdapter.kt
> +    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ProjectItemViewHolder {
минимальные доки к функциям, которые переопреледяются для создания ViewHolder? Ну это же функция, которая предоставляется RecyclerView.Adapter, который входит в гугловскую библиотеку.
Разве нужно такое документировать, когда вся документация к таким функциям находится на официальных гугловских документациях?

2019-10-27 21:16 UTC, neSpecc approved these changes

2019-10-28 14:33 UTC, nikmel2803 approved these changes

2019-10-30 20:16 UTC, merged